name: Clean Repository

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 1
        lfs: false
    
    - name: Set up Git config
      run: |
        git config user.name "Repo Cleaner Bot"
        git config user.email "cleaner-bot@github.com"
    
    - name: Delete everything except workflows
      run: |
        # Keep only .github directory and README if it exists
        find . -maxdepth 1 -type f -not -name "README.md" -delete
        find . -maxdepth 1 -type d -not -name "." -not -name ".git" -not -name ".github" -exec rm -rf {} +
        
        # Show what's left
        echo "Files remaining:"
        ls -la
        
        # Commit the deletion
        git add -A
        git commit -m "Clean repository - remove all files except workflows"
        git push origin master
        
        echo "✅ Repository cleaned. Only .github/ directory and workflows remain."
