name: Clone GitLab Master to GitHub Master

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0
        lfs: false
    
    - name: Set up Git config
      run: |
        git config user.name "GitLab Clone Bot"
        git config user.email "clone-bot@github.com"
    
    - name: Clone GitLab master to GitHub master
      run: |
        # Add GitLab remote
        git remote add gitlab https://gitlab.com/veloren/veloren.git
        
        # Configure Git to handle LFS issues
        export GIT_LFS_SKIP_SMUDGE=1
        git config lfs.allowincompletepush true
        
        # Fetch GitLab master
        echo "Fetching from GitLab..."
        git fetch gitlab master
        
        # Reset master to exactly match GitLab master
        echo "Resetting master to match GitLab..."
        git reset --hard gitlab/master
        
        # Force push to GitHub master
        echo "Pushing to GitHub master..."
        git push origin master --force
        
        # Sync tags as well
        echo "Syncing tags..."
        git fetch gitlab --tags
        git push origin --tags --force
        
        echo "✅ Successfully cloned GitLab master to GitHub master!"
