name: Sync Veloren Master from GitLab

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        lfs: false
    
    - name: Set up Git config
      run: |
        git config user.name "Veloren Sync Bot"
        git config user.email "sync-bot@github.com"
    
    - name: Add GitLab remote and sync
      run: |
        git remote add gitlab https://gitlab.com/veloren/veloren.git
        
        export GIT_LFS_SKIP_SMUDGE=1
        export GIT_LFS_SKIP_PUSH=1
        
        git fetch gitlab master
        git reset --hard gitlab/master
        git push origin master --force
        
        git fetch gitlab --tags
        git push origin --tags --force
