name: Sync Veloren Master from GitLab

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        ref: master  # Checkout master branch
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        lfs: true
    
    - name: Install and configure Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install git-lfs
        git lfs install
        # Configure to continue on LFS errors
        git config lfs.skipdownloaderrors true
    
    - name: Set up Git config
      run: |
        git config user.name "Veloren Sync Bot"
        git config user.email "sync-bot@github.com"
    
    - name: Add GitLab remote and sync
      run: |
        # Add GitLab remote
        git remote add gitlab https://gitlab.com/veloren/veloren.git
        
        # Allow incomplete LFS pushes (only push what exists)
        git config lfs.allowincompletepush true
        
        # Fetch everything from GitLab (skip LFS initially to avoid errors)
        GIT_LFS_SKIP_SMUDGE=1 git fetch gitlab master
        
        # Force reset to exactly match GitLab master
        GIT_LFS_SKIP_SMUDGE=1 git reset --hard gitlab/master
        
        # Try to download available LFS files (ignore missing ones)
        git lfs pull 2>/dev/null || echo "Downloaded available LFS files"
        
        # Force push to GitHub master (this will handle LFS files automatically)
        git push origin master --force
        
        # Sync tags as well
        git fetch gitlab --tags
        git push origin --tags --force
