name: Sync Veloren Master from GitLab

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0
        lfs: false
    
    - name: Set up Git config
      run: |
        git config user.name "Veloren Sync Bot"
        git config user.email "sync-bot@github.com"
    
    - name: Add GitLab remote and sync
      run: |
        git remote add gitlab https://gitlab.com/veloren/veloren.git
        
        # Disable Git LFS filters entirely
        git config filter.lfs.clean "cat"
        git config filter.lfs.smudge "cat" 
        git config filter.lfs.process ""
        git config filter.lfs.required false
        
        git fetch gitlab master
        git reset --hard gitlab/master
        git push origin master --force
        
        git fetch gitlab --tags
        git push origin --tags --force
